version: "2"
services:
  app:
    container_name: ReactMaterial
    restart: always
    build: .
    ports:
      - "5000:5000"
      - "8080:80"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  node:
    container_name: node
    images: node
    ports:
      